In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/NFHS_DATASET.csv')

In [2]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(707, 109)

In [3]:
print("\nColumns:")
for col in df.columns:
    print(col)

Columns:
District Names
State/UT
Number of Households surveyed
Number of Women age 15-49 years interviewed
Number of Men age 15-54 years interviewed
Female population age 6 years and above who ever attended school (%)
Population below age 15 years (%)
 Sex ratio of the total population (females per 1,000 males)
Sex ratio at birth for children born in the last five years (females per 1,000 males)
Children under age 5 years whose birth was registered with the civil authority (%)
Deaths in the last 3 years registered with the civil authority (%)
Population living in households with electricity (%)
Population living in households with an improved drinking-water source1 (%)
Population living in households that use an improved sanitation facility2 (%)
Households using clean fuel for cooking3 (%)
Households using iodized salt (%)
Households with any usual member covered under a health insurance/financing scheme (%)
Children age 5 years who attended pre-primary school during the school year 2019-20 (%)
Women (age 15-49) who are literate4 (%)
Women (age 15-49)  with 10 or more years of schooling (%)
Women age 20-24 years married before age 18 years (%)
Births in the 5 years preceding the survey that are third or higher order (%)
Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)
Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any method6 (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any modern method6 (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Female sterilization (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Male sterilization (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - IUD/PPIUD (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Pill (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Condom (%)
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Injectables (%)
Total Unmet need for Family Planning (Currently Married Women Age 15-49  years)7 (%)
Unmet need for spacing (Currently Married Women Age 15-49  years)7 (%)
Health worker ever talked to female non-users about family planning (%)
Current users ever told about side effects of current method of family planning8 (%)
Mothers who had an antenatal check-up in the first trimester  (for last birth in the 5 years before the survey) (%)
Mothers who had at least 4 antenatal care visits  (for last birth in the 5 years before the survey) (%)
Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%)
Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%)
Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%)
Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%)
Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)
Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.)
Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%)
Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)
Institutional births (in the 5 years before the survey) (%)
Institutional births in public facility (in the 5 years before the survey) (%)
Home births that were conducted by skilled health personnel  (in the 5 years before the survey)10 (%)
Births attended by skilled health personnel (in the 5 years before the survey)10 (%)
Births delivered by caesarean section (in the 5 years before the survey) (%)
Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%)
Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%)
Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)
Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)
Children age 12-23 months who have received BCG (%)
Children age 12-23 months who have received 3 doses of polio vaccine13 (%)
Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%)
Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%)
Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%)
Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%)
Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%)
Children age 9-35 months who received a vitamin A dose in the last 6 months (%)
Children age 12-23 months who received most of their vaccinations in a public health facility (%)
Children age 12-23 months who received most of their vaccinations in a private health facility (%)
Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%)
Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%)
Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%)
Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)
Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%)
Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)
Children under age 3 years breastfed within one hour of birth15 (%)
Children under age 6 months exclusively breastfed16 (%)
Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%)
Breastfeeding children age 6-23 months receiving an adequate diet16, 17  (%)
Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)
Total children age 6-23 months receiving an adequate diet16, 17  (%)
Children under 5 years who are stunted (height-for-age)18 (%)
Children under 5 years who are wasted (weight-for-height)18 (%)
Children under 5 years who are severely wasted (weight-for-height)19 (%)
Children under 5 years who are underweight (weight-for-age)18 (%)
Children under 5 years who are overweight (weight-for-height)20 (%)
Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)
Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%)
Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%)
Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)
Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)
Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)
All women age 15-49 years who are anaemic22 (%)
All women age 15-19 years who are anaemic22 (%)
Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)
Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)
Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)
Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)
Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)
Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)
Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)
Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)
Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)
Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)
Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)
Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)
Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)
Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)
Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)
Women age 15 years and above who use any kind of tobacco (%)
Men age 15 years and above who use any kind of tobacco (%)
Women age 15 years and above who consume alcohol (%)
Men age 15 years and above who consume alcohol (%)

In [4]:
print("\nFirst 5 Records:")
display(df.head())

First 5 Records:

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,*,764,125,78.0,23.0,973,927,98.0,...,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,North & Middle Andaman,Andaman & Nicobar Islands,874,(45.7),108,82.7,19.8,950,844,100.0,...,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,South Andaman,Andaman & Nicobar Islands,868,844,150,84.7,21.0,967,935,96.5,...,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,Srikakulam,Andhra Pradesh,874,780,100,-5.0,20.7,1140,1163,95.0,...,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,Vizianagaram,Andhra Pradesh,902,853,134,56.0,NaN,1114,898,95.4,...,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3

In [5]:
print("\nLast 5 Records:")
display(df.tail())

Last 5 Records:

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
702,South Twenty Four Pargana,West Bengal,917,1089,148,80.9,25.5,1055,1099,97.6,...,13.0,4.3,19.1,0.0,0.0,0.2,6.3,49.8,0.4,16.5
703,Paschim Medinipur,West Bengal,910,1002,137,72.1,23.4,1089,1005,99.3,...,10.7,4.3,19.0,0.0,0.0,0.0,18.8,50.5,1.5,20.8
704,Purba Medinipur,West Bengal,873,957,131,83.0,23.9,1031,777,99.3,...,11.9,4.4,21.3,0.0,0.2,0.5,12.9,40.1,2.0,14.8
705,Paschim Barddhaman,West Bengal,912,1190,184,74.8,22.3,977,787,97.7,...,14.5,3.7,20.7,0.7,1.3,0.4,11.8,40.2,0.8,14.6
706,Nicobars,Andaman & Nicobar Islands,*,764,125,78.0,23.0,973,927,98.0,...,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Columns: 109 entries, District Names to Men age 15 years and above who consume alcohol (%)
dtypes: float64(54), int64(2), object(53)
memory usage: 602.2+ KB

In [7]:
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
Number of Men age 15-54 years interviewed,707.0,143.971711,31.951837,17.0,124.000,145.0,164.00,241.0
Female population age 6 years and above who ever attended school (%),707.0,71.431683,10.700749,-5.0,64.400,71.4,78.95,99.2
Population below age 15 years (%),706.0,26.371246,5.294883,16.0,22.525,25.4,29.50,50.6
"Sex ratio of the total population (females per 1,000 males)",707.0,1020.572843,73.369925,755.0,969.000,1013.0,1065.50,1332.0
Children under age 5 years whose birth was registered with the civil authority (%),707.0,91.066337,9.389647,51.6,87.050,94.9,97.75,100.0
Population living in households with electricity (%),707.0,97.002970,4.351725,68.4,96.400,98.7,99.50,100.0
Population living in households with an improved drinking-water source1 (%),707.0,93.730127,8.714126,41.2,92.000,97.0,99.30,100.0
Population living in households that use an improved sanitation facility2 (%),707.0,71.948515,14.287484,29.2,62.000,73.8,83.35,99.9
Households using clean fuel for cooking3 (%),707.0,54.127016,24.165069,8.6,34.000,50.6,75.15,99.8
Households using iodized salt (%),707.0,95.135644,5.481765,47.9,93.800,97.0,98.60,100.0
Households with any usual member covered under a health insurance/financing scheme (%),707.0,40.176096,23.103115,1.2,20.200,35.7,59.95,97.8
Women (age 15-49) who are literate4 (%),707.0,74.350495,12.250455,38.6,66.850,75.1,83.75,99.7
Women (age 15-49) with 10 or more years of schooling (%),707.0,40.345403,14.224272,13.6,29.300,39.2,49.90,88.2
Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%),707.0,78.302970,15.247762,9.0,67.700,79.6,92.20,100.0
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any method6 (%),707.0,65.775813,12.170536,12.1,58.650,68.1,75.00,89.1
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any modern method6 (%),707.0,54.831825,13.557792,10.6,46.500,55.6,65.55,81.2
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Female sterilization (%),707.0,35.142857,18.767047,1.1,19.150,34.2,49.80,76.5
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Male sterilization (%),707.0,0.519236,1.620224,0.0,0.000,0.1,0.35,18.4
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - IUD/PPIUD (%),707.0,2.886704,3.429611,0.0,1.000,1.9,3.55,32.2
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Pill (%),707.0,5.601556,8.065771,0.0,1.100,2.5,5.95,53.0
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Condom (%),707.0,8.962659,8.059147,0.0,3.100,6.1,12.35,43.9
Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Injectables (%),707.0,0.630835,1.091447,0.0,0.100,0.3,0.70,9.8
Total Unmet need for Family Planning (Currently Married Women Age 15-49 years)7 (%),707.0,9.562942,5.039932,1.2,5.800,8.5,12.30,33.0
Unmet need for spacing (Currently Married Women Age 15-49 years)7 (%),707.0,4.290948,2.781969,0.3,2.600,3.7,5.20,25.2
Health worker ever talked to female non-users about family planning (%),707.0,24.247242,10.317007,2.0,16.900,23.1,30.25,64.2
Institutional births (in the 5 years before the survey) (%),707.0,88.677935,12.003841,21.4,83.700,92.2,97.40,100.0
Institutional births in public facility (in the 5 years before the survey) (%),707.0,64.982885,16.356891,18.1,53.350,66.5,76.95,96.7
Home births that were conducted by skilled health personnel (in the 5 years before the survey)10 (%),707.0,3.077369,3.165778,0.0,0.800,2.1,4.40,19.9
Births attended by skilled health personnel (in the 5 years before the survey)10 (%),707.0,89.584158,9.919516,30.9,84.850,92.3,97.00,100.0
Births delivered by caesarean section (in the 5 years before the survey) (%),707.0,22.826308,15.980752,1.4,10.700,18.6,30.75,82.4
Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%),707.0,6.475248,4.093371,0.0,3.700,5.5,8.70,39.3
Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%),707.0,2.537765,2.059450,0.0,0.900,2.1,3.75,11.2
Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),707.0,17.881188,7.454082,1.2,12.650,18.0,23.10,43.6
Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%),707.0,23.092221,10.620304,3.8,14.900,21.3,30.25,53.0
Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%),707.0,57.471711,13.864376,18.0,48.800,58.2,67.10,96.6
Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%),707.0,56.137199,12.028755,15.6,49.350,57.5,63.80,94.6
All women age 15-49 years who are anaemic22 (%),707.0,55.892362,11.955941,14.9,49.150,57.2,63.60,93.5
Women age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%),707.0,5.840028,1.839301,1.6,4.500,5.7,7.00,14.6
Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),707.0,5.589533,2.820243,0.7,3.600,4.9,7.10,18.0
Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),707.0,12.462518,4.619385,4.1,9.000,11.7,15.25,32.1
Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%),707.0,7.001697,2.112159,1.7,5.450,6.8,8.30,18.3
Men (age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),707.0,6.642999,3.115317,0.5,4.400,6.3,8.30,21.1
Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),707.0,14.723197,4.944597,4.8,11.100,14.1,17.60,36.2
Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),707.0,12.686846,3.148287,4.3,10.500,12.6,14.55,23.7
Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),707.0,5.353890,1.953966,0.7,4.000,5.1,6.50,15.8
Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),707.0,21.426591,5.239580,8.5,17.600,21.0,24.50,42.1
Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),707.0,16.288402,4.379340,5.3,13.200,16.3,18.90,32.9
Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),707.0,6.059689,2.578057,0.8,4.100,5.8,7.60,19.5
Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),707.0,24.806223,6.813827,10.0,19.800,24.4,29.00,49.6
Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),707.0,1.591089,2.808287,0.0,0.200,0.6,1.50,23.2
Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),707.0,0.675389,1.637923,0.0,0.000,0.2,0.50,14.6
Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),707.0,0.712588,1.478408,0.0,0.000,0.3,0.70,15.8
Women age 15 years and above who use any kind of tobacco (%),707.0,11.695615,12.099985,0.1,4.100,7.7,14.80,70.6
Men age 15 years and above who use any kind of tobacco (%),707.0,40.643140,14.142903,6.8,30.400,42.5,51.00,80.6
Women age 15 years and above who consume alcohol (%),707.0,2.960113,6.161720,0.0,0.300,0.5,1.70,42.8
Men age 15 years and above who consume alcohol (%),707.0,23.253607,13.453646,0.1,13.600,20.2,31.10,68.4