# 1. Data Loading

**Purpose:** Load the original NFHS dataset and look at what it contains.

**Library used:** pandas and NumPy only.

Keep this notebook for loading and viewing the original data. Data cleaning is handled in a separate notebook.

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

## Step 1: Load the dataset

Place `NFHS_DATASET.csv` in the same folder as this notebook. If you are using Google Colab, upload the file with this exact name.

In [2]:
file_name = "NFHS_DATASET.csv"
df = pd.read_csv(file_name)

## Step 2: Check the size

This tells us how many rows and columns are in the file.

In [3]:
print("Number of rows and columns:", df.shape)

Number of rows and columns: (707, 109)

## Step 3: View the first few rows

This helps us see how the data is arranged.

In [4]:
df.head()

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),Deaths in the last 3 years registered with the civil authority (%),Population living in households with electricity (%),Population living in households with an improved drinking-water source1 (%),Population living in households that use an improved sanitation facility2 (%),Households using clean fuel for cooking3 (%),Households using iodized salt (%),Households with any usual member covered under a health insurance/financing scheme (%),Children age 5 years who attended pre-primary school during the school year 2019-20 (%),Women (age 15-49) who are literate4 (%),Women (age 15-49) with 10 or more years of schooling (%),Women age 20-24 years married before age 18 years (%),Births in the 5 years preceding the survey that are third or higher order (%),Women age 15-19 years who were already mothers or pregnant at the time of the survey (%),Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any method6 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any modern method6 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Female sterilization (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Male sterilization (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - IUD/PPIUD (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Pill (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Condom (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Injectables (%),Total Unmet need for Family Planning (Currently Married Women Age 15-49 years)7 (%),Unmet need for spacing (Currently Married Women Age 15-49 years)7 (%),Health worker ever talked to female non-users about family planning (%),Current users ever told about side effects of current method of family planning8 (%),Mothers who had an antenatal check-up in the first trimester (for last birth in the 5 years before the survey) (%),Mothers who had at least 4 antenatal care visits (for last birth in the 5 years before the survey) (%),Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%),Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%),Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%),Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%),Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%),Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.),Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%),Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%),Institutional births (in the 5 years before the survey) (%),Institutional births in public facility (in the 5 years before the survey) (%),Home births that were conducted by skilled health personnel (in the 5 years before the survey)10 (%),Births attended by skilled health personnel (in the 5 years before the survey)10 (%),Births delivered by caesarean section (in the 5 years before the survey) (%),Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%),Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%),Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%),Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%),Children age 12-23 months who have received BCG (%),Children age 12-23 months who have received 3 doses of polio vaccine13 (%),Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%),Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%),Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%),Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%),Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%),Children age 9-35 months who received a vitamin A dose in the last 6 months (%),Children age 12-23 months who received most of their vaccinations in a public health facility (%),Children age 12-23 months who received most of their vaccinations in a private health facility (%),Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%),Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%),Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%),Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%),Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children under age 3 years breastfed within one hour of birth15 (%),Children under age 6 months exclusively breastfed16 (%),Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%),"Breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Total children age 6-23 months receiving an adequate diet16, 17 (%)",Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are wasted (weight-for-height)18 (%),Children under 5 years who are severely wasted (weight-for-height)19 (%),Children under 5 years who are underweight (weight-for-age)18 (%),Children under 5 years who are overweight (weight-for-height)20 (%),Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%),Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%),Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%),Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%),Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%),All women age 15-49 years who are anaemic22 (%),All women age 15-19 years who are anaemic22 (%),Women age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%),Men (age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,*,764,125,78.0,23.0,973,927,98.0,83.2,97.9,98.8,83.5,56.9,99.4,2.7,(29.5),87.5,53.5,11.4,0.0,1.8,100.0,65.3,57.2,46.4,0.0,2.7,2.0,4.9,1.2,9.5,3.3,40.4,49.4,62.8,71.7,78.0,72.6,43.9,97.9,85.1,2278,*,92.5,97.8,96.7,0.8,98.6,11.5,*,10.7,(64.2),(94.1),(80.4),(69.1),(71.9),(67.3),(20.7),(3.1),(68.6),94.9,(100.0),(0.0),5.7,*,*,*,1.8,(85.7),55.4,*,*,(19.4),*,(18.7),21.6,15.7,7.8,24.6,1.5,8.2,39.1,62.5,37.7,38.4,*,38.3,48.0,7.4,3.9,13.1,9.6,4.4,15.4,23.2,8.5,35.4,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,North & Middle Andaman,Andaman & Nicobar Islands,874,(45.7),108,82.7,19.8,950,844,100.0,(92.6),93.2,92.2,86.4,61.3,99.9,2.1,(30.1),84.0,41.0,15.4,1.5,3.8,100.0,84.1,73.1,48.3,0.6,6.4,7.8,9.3,0.0,5.8,1.3,23.2,83.2,74.5,79.2,91.1,83.7,24.1,99.2,92.5,1904,*,94.3,97.7,95.0,0.7,98.3,12.9,*,11.4,*,*,*,*,*,*,*,*,*,(89.6),*,*,4.5,*,*,*,7.0,*,27.3,*,*,(6.5),*,(5.9),27.0,27.0,8.3,42.8,0.8,8.6,35.9,79.3,30.4,62.5,*,62.1,47.8,7.2,6.4,16.7,9.1,6.9,18.3,18.4,4.0,27.4,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,South Andaman,Andaman & Nicobar Islands,868,844,150,84.7,21.0,967,935,96.5,92.2,99.6,97.9,89.3,91.9,99.7,1.2,(50.8),86.7,57.5,17.1,0.5,2.8,98.2,57.1,50.5,34.0,0.0,2.8,1.8,10.6,0.3,17.6,8.6,31.2,88.2,79.4,85.9,92.1,81.0,61.9,98.9,88.1,3460,*,89.8,99.5,83.8,0.0,96.9,37.1,(79.1),29.6,(76.3),(96.6),(100.0),(79.0),(94.8),(81.7),(33.7),(0.0),(85.3),84.0,(93.1),(4.3),6.0,*,*,*,0.0,(77.3),51.1,*,*,(22.3),*,23.5,21.1,12.6,3.5,17.4,7.2,10.0,39.0,78.2,43.4,57.6,*,57.7,43.2,7.5,9.5,18.4,9.3,7.8,18.1,12.7,4.9,23.0,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,Srikakulam,Andhra Pradesh,874,780,100,-5.0,20.7,1140,1163,95.0,71.0,99.9,87.7,71.6,74.7,76.5,75.6,(0.0),64.3,42.5,25.4,0.0,5.5,78.0,72.3,72.2,71.0,0.3,0.6,0.0,0.3,0.0,5.7,3.6,16.0,45.8,79.7,78.4,94.4,67.5,35.3,100.0,90.8,3479,*,97.7,97.9,52.2,0.5,96.4,57.0,73.8,44.5,(82.8),(100.0),(93.3),(82.8),(89.7),(93.3),(34.9),(74.8),(89.7),69.6,(97.0),(3.0),11.9,*,*,*,1.3,(79.7),42.8,*,*,(14.0),*,16.1,19.7,19.5,7.4,21.4,4.5,13.8,27.2,54.0,59.6,62.8,*,62.6,59.2,8.2,7.8,17.4,6.8,8.6,17.6,12.8,5.9,22.1,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,Vizianagaram,Andhra Pradesh,902,853,134,56.0,NaN,1114,898,95.4,81.7,99.5,93.1,61.7,60.3,85.0,76.7,(25.2),58.3,37.6,33.7,2.2,12.7,72.5,71.2,71.2,69.3,1.3,0.0,0.0,0.6,0.0,6.7,4.7,21.1,36.4,76.1,71.4,91.3,59.6,32.4,98.8,83.9,1931,*,89.2,99.0,70.6,0.5,97.6,41.3,70.3,30.3,(76.8),*,(100.0),(76.8),(90.3),(92.5),(35.0),(77.3),(83.6),85.9,(100.0),(0.0),7.5,*,*,*,1.4,(83.5),55.6,*,*,(2.5),*,1.8,36.4,19.2,8.3,32.2,4.7,16.9,28.8,58.0,66.7,64.6,*,64.0,73.9,6.2,7.0,14.3,5.8,7.5,14.5,12.9,6.6,25.2,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3

## Step 4: View the last few rows

This gives us a quick look at the end of the file.

In [5]:
df.tail()

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),Deaths in the last 3 years registered with the civil authority (%),Population living in households with electricity (%),Population living in households with an improved drinking-water source1 (%),Population living in households that use an improved sanitation facility2 (%),Households using clean fuel for cooking3 (%),Households using iodized salt (%),Households with any usual member covered under a health insurance/financing scheme (%),Children age 5 years who attended pre-primary school during the school year 2019-20 (%),Women (age 15-49) who are literate4 (%),Women (age 15-49) with 10 or more years of schooling (%),Women age 20-24 years married before age 18 years (%),Births in the 5 years preceding the survey that are third or higher order (%),Women age 15-19 years who were already mothers or pregnant at the time of the survey (%),Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any method6 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any modern method6 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Female sterilization (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Male sterilization (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - IUD/PPIUD (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Pill (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Condom (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Injectables (%),Total Unmet need for Family Planning (Currently Married Women Age 15-49 years)7 (%),Unmet need for spacing (Currently Married Women Age 15-49 years)7 (%),Health worker ever talked to female non-users about family planning (%),Current users ever told about side effects of current method of family planning8 (%),Mothers who had an antenatal check-up in the first trimester (for last birth in the 5 years before the survey) (%),Mothers who had at least 4 antenatal care visits (for last birth in the 5 years before the survey) (%),Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%),Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%),Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%),Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%),Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%),Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.),Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%),Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%),Institutional births (in the 5 years before the survey) (%),Institutional births in public facility (in the 5 years before the survey) (%),Home births that were conducted by skilled health personnel (in the 5 years before the survey)10 (%),Births attended by skilled health personnel (in the 5 years before the survey)10 (%),Births delivered by caesarean section (in the 5 years before the survey) (%),Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%),Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%),Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%),Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%),Children age 12-23 months who have received BCG (%),Children age 12-23 months who have received 3 doses of polio vaccine13 (%),Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%),Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%),Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%),Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%),Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%),Children age 9-35 months who received a vitamin A dose in the last 6 months (%),Children age 12-23 months who received most of their vaccinations in a public health facility (%),Children age 12-23 months who received most of their vaccinations in a private health facility (%),Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%),Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%),Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%),Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%),Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children under age 3 years breastfed within one hour of birth15 (%),Children under age 6 months exclusively breastfed16 (%),Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%),"Breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Total children age 6-23 months receiving an adequate diet16, 17 (%)",Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are wasted (weight-for-height)18 (%),Children under 5 years who are severely wasted (weight-for-height)19 (%),Children under 5 years who are underweight (weight-for-age)18 (%),Children under 5 years who are overweight (weight-for-height)20 (%),Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%),Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%),Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%),Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%),Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%),All women age 15-49 years who are anaemic22 (%),All women age 15-19 years who are anaemic22 (%),Women age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%),Men (age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
702,South Twenty Four Pargana,West Bengal,917,1089,148,80.9,25.5,1055,1099,97.6,84.1,99.2,100.0,70.1,36.2,94.1,36.7,21.4,85.6,34.9,41.9,0.0,13.1,80.3,82.9,67.9,21.9,0.1,2.8,34.8,5.4,1.1,3.7,1.7,17.7,54.5,77.1,87.5,96.4,67.2,32.7,98.6,67.0,2142,*,70.8,91.0,77.7,2.2,93.2,26.6,(72.3),21.8,91.7,96.3,100.0,95.1,94.9,94.8,37.4,1.7,95.0,58.8,100.0,0.0,4.5,*,*,*,1.6,(60.9),46.2,(73.5),*,27.2,*,27.6,36.7,21.2,11.8,32.2,7.0,9.9,21.2,86.0,70.4,62.1,(47.4),61.6,57.3,7.2,8.2,16.5,9.8,10.1,21.3,13.5,5.6,21.5,13.0,4.3,19.1,0.0,0.0,0.2,6.3,49.8,0.4,16.5
703,Paschim Medinipur,West Bengal,910,1002,137,72.1,23.4,1089,1005,99.3,78.8,95.4,95.5,58.3,17.5,93.8,25.8,41.5,70.9,26.2,55.7,0.4,25.0,67.3,60.7,55.6,32.1,0.4,1.4,18.0,3.1,0.5,11.5,5.7,23.5,49.3,52.6,63.1,96.2,64.3,31.9,99.1,79.7,3388,*,80.9,87.6,72.0,5.1,95.1,23.1,(63.6),18.3,76.9,86.8,100.0,80.1,93.7,89.3,40.6,0.0,89.0,78.3,93.3,0.0,6.3,*,*,*,1.4,72.1,67.9,*,*,20.9,*,21.8,31.1,30.3,9.6,40.0,1.7,18.9,19.1,64.5,66.0,82.0,(62.9),81.5,84.5,9.3,7.8,17.9,9.9,10.5,21.7,9.1,5.0,19.3,10.7,4.3,19.0,0.0,0.0,0.0,18.8,50.5,1.5,20.8
704,Purba Medinipur,West Bengal,873,957,131,83.0,23.9,1031,777,99.3,86.2,99.0,87.8,69.8,17.0,90.0,21.5,23.3,77.0,30.9,57.6,0.0,22.0,78.4,59.3,48.1,16.4,0.0,1.2,26.2,3.5,0.1,12.3,4.1,20.6,50.0,69.3,56.8,87.1,51.6,32.9,98.8,48.5,4390,*,58.1,91.5,71.5,4.6,94.6,36.1,76.0,29.3,88.4,(74.3),100.0,90.6,91.7,91.7,52.5,9.5,90.0,83.7,98.0,0.0,8.9,*,*,*,3.8,72.5,59.4,*,*,21.5,*,20.9,25.8,15.5,3.0,30.6,3.1,16.5,27.4,66.2,67.5,70.5,(66.4),70.4,73.8,8.8,11.0,21.3,10.8,11.9,24.0,9.6,4.7,18.1,11.9,4.4,21.3,0.0,0.2,0.5,12.9,40.1,2.0,14.8
705,Paschim Barddhaman,West Bengal,912,1190,184,74.8,22.3,977,787,97.7,77.9,97.0,95.2,71.5,56.3,89.8,21.8,10.2,73.5,37.1,31.8,2.1,15.4,84.4,65.3,54.0,28.2,0.0,2.1,13.4,8.8,0.1,12.0,3.6,13.7,25.8,70.3,70.4,96.6,57.0,30.8,95.5,64.1,3020,*,70.5,89.8,62.7,0.8,91.3,34.3,69.1,24.8,62.4,69.7,95.9,62.4,90.8,89.4,48.6,0.0,90.3,60.6,97.6,2.4,8.8,(81.2),(48.9),(69.7),2.0,86.3,59.3,*,*,31.4,*,31.1,39.7,25.5,8.0,41.0,3.1,18.4,20.4,67.1,74.7,66.5,49.4,65.8,65.6,8.5,7.0,16.2,12.2,10.3,23.4,9.6,4.3,17.6,14.5,3.7,20.7,0.7,1.3,0.4,11.8,40.2,0.8,14.6
706,Nicobars,Andaman & Nicobar Islands,*,764,125,78.0,23.0,973,927,98.0,83.2,97.9,98.8,83.5,56.9,99.4,2.7,(29.5),87.5,53.5,11.4,0.0,1.8,100.0,65.3,57.2,46.4,0.0,2.7,2.0,4.9,1.2,9.5,3.3,40.4,49.4,62.8,71.7,78.0,72.6,43.9,97.9,85.1,2278,*,92.5,97.8,96.7,0.8,98.6,11.5,*,10.7,(64.2),(94.1),(80.4),(69.1),(71.9),(67.3),(20.7),(3.1),(68.6),94.9,(100.0),(0.0),5.7,*,*,*,1.8,(85.7),55.4,*,*,(19.4),*,(18.7),21.6,15.7,7.8,24.6,1.5,8.2,39.1,62.5,37.7,38.4,*,38.3,48.0,7.4,3.9,13.1,9.6,4.4,15.4,23.2,8.5,35.4,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5

## Step 5: Display the column names

This helps us find the names of the columns available for our project.

In [6]:
print(df.columns.tolist())

['District Names', 'State/UT', 'Number of Households surveyed', 'Number of Women age 15-49 years interviewed', 'Number of Men age 15-54 years interviewed', 'Female population age 6 years and above who ever attended school (%)', 'Population below age 15 years (%)', ' Sex ratio of the total population (females per 1,000 males)', 'Sex ratio at birth for children born in the last five years (females per 1,000 males)', 'Children under age 5 years whose birth was registered with the civil authority (%)', 'Deaths in the last 3 years registered with the civil authority (%)', 'Population living in households with electricity (%)', 'Population living in households with an improved drinking-water source1 (%)', 'Population living in households that use an improved sanitation facility2 (%)', 'Households using clean fuel for cooking3 (%)', 'Households using iodized salt (%)', 'Households with any usual member covered under a health insurance/financing scheme (%)', 'Children age 5 years who attended pre-primary school during the school year 2019-20 (%)', 'Women (age 15-49) who are literate4 (%)', 'Women (age 15-49)  with 10 or more years of schooling (%)', 'Women age 20-24 years married before age 18 years (%)', 'Births in the 5 years preceding the survey that are third or higher order (%)', 'Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)', 'Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any method6 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any modern method6 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Female sterilization (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Male sterilization (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - IUD/PPIUD (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Pill (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Condom (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Injectables (%)', 'Total Unmet need for Family Planning (Currently Married Women Age 15-49  years)7 (%)', 'Unmet need for spacing (Currently Married Women Age 15-49  years)7 (%)', 'Health worker ever talked to female non-users about family planning (%)', 'Current users ever told about side effects of current method of family planning8 (%)', 'Mothers who had an antenatal check-up in the first trimester  (for last birth in the 5 years before the survey) (%)', 'Mothers who had at least 4 antenatal care visits  (for last birth in the 5 years before the survey) (%)', 'Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%)', 'Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%)', 'Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%)', 'Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%)', 'Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)', 'Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.)', 'Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%)', 'Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)', 'Institutional births (in the 5 years before the survey) (%)', 'Institutional births in public facility (in the 5 years before the survey) (%)', 'Home births that were conducted by skilled health personnel  (in the 5 years before the survey)10 (%)', 'Births attended by skilled health personnel (in the 5 years before the survey)10 (%)', 'Births delivered by caesarean section (in the 5 years before the survey) (%)', 'Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%)', 'Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%)', "Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)", 'Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)', 'Children age 12-23 months who have received BCG (%)', 'Children age 12-23 months who have received 3 doses of polio vaccine13 (%)', 'Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%)', 'Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%)', 'Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%)', 'Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%)', 'Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%)', 'Children age 9-35 months who received a vitamin A dose in the last 6 months (%)', 'Children age 12-23 months who received most of their vaccinations in a public health facility (%)', 'Children age 12-23 months who received most of their vaccinations in a private health facility (%)', 'Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%) ', 'Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%) ', 'Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%) ', 'Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%) ', 'Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%) ', 'Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)  ', 'Children under age 3 years breastfed within one hour of birth15 (%)', 'Children under age 6 months exclusively breastfed16 (%)', 'Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%)', 'Breastfeeding children age 6-23 months receiving an adequate diet16, 17  (%)', 'Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)', 'Total children age 6-23 months receiving an adequate diet16, 17  (%)', 'Children under 5 years who are stunted (height-for-age)18 (%)', 'Children under 5 years who are wasted (weight-for-height)18 (%)', 'Children under 5 years who are severely wasted (weight-for-height)19 (%)', 'Children under 5 years who are underweight (weight-for-age)18 (%)', 'Children under 5 years who are overweight (weight-for-height)20 (%)', 'Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)', 'Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%)', 'Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%)', 'Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)', 'Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)', 'Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)', 'All women age 15-49 years who are anaemic22 (%)', 'All women age 15-19 years who are anaemic22 (%) ', 'Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)', 'Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)', 'Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)', 'Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)', 'Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)', 'Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)', 'Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)', 'Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)', 'Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)', 'Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)', 'Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)', 'Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)', 'Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)', 'Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)', 'Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)', 'Women age 15 years and above who use any kind of tobacco (%)', 'Men age 15 years and above who use any kind of tobacco (%)', 'Women age 15 years and above who consume alcohol (%)', 'Men age 15 years and above who consume alcohol (%)']

## Step 6: Check the column data types

This shows whether each column contains text, numbers, or other types of values. We are only checking the data here; we are not changing it.

In [7]:
print(df.dtypes)

District Names                                                                                                                                                                       object
State/UT                                                                                                                                                                             object
Number of Households surveyed                                                                                                                                                        object
Number of Women age 15-49 years interviewed                                                                                                                                          object
Number of Men age 15-54 years interviewed                                                                                                                                             int64
Female population age 6 years and above who ever attended school (%)                                                                                                                float64
Population below age 15 years (%)                                                                                                                                                   float64
 Sex ratio of the total population (females per 1,000 males)                                                                                                                          int64
Sex ratio at birth for children born in the last five years (females per 1,000 males)                                                                                                object
Children under age 5 years whose birth was registered with the civil authority (%)                                                                                                  float64
Deaths in the last 3 years registered with the civil authority (%)                                                                                                                   object
Population living in households with electricity (%)                                                                                                                                float64
Population living in households with an improved drinking-water source1 (%)                                                                                                         float64
Population living in households that use an improved sanitation facility2 (%)                                                                                                       float64
Households using clean fuel for cooking3 (%)                                                                                                                                        float64
Households using iodized salt (%)                                                                                                                                                   float64
Households with any usual member covered under a health insurance/financing scheme (%)                                                                                              float64
Children age 5 years who attended pre-primary school during the school year 2019-20 (%)                                                                                              object
Women (age 15-49) who are literate4 (%)                                                                                                                                             float64
Women (age 15-49)  with 10 or more years of schooling (%)                                                                                                                           float64
Women age 20-24 years married before age 18 years (%)                                                                                                                                object
Births in the 5 years preceding the survey that are third or higher order (%)                                                                                                        object
Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)                                                                                             object
Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)                                                                                     float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any method6 (%)                                                                                 float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any modern method6 (%)                                                                          float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Female sterilization (%)                                                                        float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Male sterilization (%)                                                                          float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - IUD/PPIUD (%)                                                                                   float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Pill (%)                                                                                        float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Condom (%)                                                                                      float64
Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Injectables (%)                                                                                 float64
Total Unmet need for Family Planning (Currently Married Women Age 15-49  years)7 (%)                                                                                                float64
Unmet need for spacing (Currently Married Women Age 15-49  years)7 (%)                                                                                                              float64
Health worker ever talked to female non-users about family planning (%)                                                                                                             float64
Current users ever told about side effects of current method of family planning8 (%)                                                                                                 object
Mothers who had an antenatal check-up in the first trimester  (for last birth in the 5 years before the survey) (%)                                                                  object
Mothers who had at least 4 antenatal care visits  (for last birth in the 5 years before the survey) (%)                                                                              object
Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%)                                                               object
Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%)                                              object
Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%)                                              object
Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%)                                  object
Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)       object
Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.)                                                   object
Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%)                              object
Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)     object
Institutional births (in the 5 years before the survey) (%)                                                                                                                         float64
Institutional births in public facility (in the 5 years before the survey) (%)                                                                                                      float64
Home births that were conducted by skilled health personnel  (in the 5 years before the survey)10 (%)                                                                               float64
Births attended by skilled health personnel (in the 5 years before the survey)10 (%)                                                                                                float64
Births delivered by caesarean section (in the 5 years before the survey) (%)                                                                                                        float64
Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%)                                                                  object
Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%)                                                                   object
Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)                                                                object
Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)                                                                                     object
Children age 12-23 months who have received BCG (%)                                                                                                                                  object
Children age 12-23 months who have received 3 doses of polio vaccine13 (%)                                                                                                           object
Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%)                                                                                                      object
Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%)                                                                                   object
Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%)                                                                                    object
Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%)                                                                                                       object
Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%)                                                                                              object
Children age 9-35 months who received a vitamin A dose in the last 6 months (%)                                                                                                      object
Children age 12-23 months who received most of their vaccinations in a public health facility (%)                                                                                    object
Children age 12-23 months who received most of their vaccinations in a private health facility (%)                                                                                   object
Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%)                                                                                        float64
Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%)                                               object
Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%)                                                                       object
Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)                                          object
Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%)                                           float64
Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)                            object
Children under age 3 years breastfed within one hour of birth15 (%)                                                                                                                  object
Children under age 6 months exclusively breastfed16 (%)                                                                                                                              object
Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%)                                                                                                      object
Breastfeeding children age 6-23 months receiving an adequate diet16, 17  (%)                                                                                                         object
Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)                                                                                                      object
Total children age 6-23 months receiving an adequate diet16, 17  (%)                                                                                                                 object
Children under 5 years who are stunted (height-for-age)18 (%)                                                                                                                        object
Children under 5 years who are wasted (weight-for-height)18 (%)                                                                                                                      object
Children under 5 years who are severely wasted (weight-for-height)19 (%)                                                                                                             object
Children under 5 years who are underweight (weight-for-age)18 (%)                                                                                                                    object
Children under 5 years who are overweight (weight-for-height)20 (%)                                                                                                                  object
Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)                                                                                         float64
Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%)                                                                                                         float64
Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%)                                                                                                           float64
Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)                                                                                                                          object
Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)                                                                                                               float64
Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)                                                                                                                    object
All women age 15-49 years who are anaemic22 (%)                                                                                                                                     float64
All women age 15-19 years who are anaemic22 (%)                                                                                                                                      object
Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)                                                                                                     float64
Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)                                                                                                     float64
Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)                                             float64
Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)                                                                                                         float64
Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)                                                                                                     float64
Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)                                              float64
Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)                                                     float64
Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)                                         float64
Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)                    float64
Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)                                                       float64
Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)                                           float64
Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)                      float64
Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)                                                                                                     float64
Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)                                                                                                   float64
Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)                                                                                               float64
Women age 15 years and above who use any kind of tobacco (%)                                                                                                                        float64