In [1]:
import pandas as pd
import numpy as np

# Load the cleaned dataset produced by Data Validation & Cleaning
df = pd.read_excel("AnemiaPrevalence_Selected_cols_Verified.xlsx")

print("Cleaned dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Cleaned dataset loaded successfully!
Dataset shape: (706, 16)

,District,State,Women_Literacy,Women_Schooling,Teenage_Pregnancy,IFA_Consumption,Institutional_Births,Low_BMI,Improved_Sanitation,Clean_Cooking_Fuel,Health_Insurance,Women_Anemia,Children_Anemia,NonPregnant_Anemia,Pregnant_Anemia,Teen_Women_Anemia
0,Nicobars,Andaman & Nicobar Islands,87.5,53.5,1.8,72.6,97.8,8.2,83.5,56.9,2.7,38.3,37.7,38.4,51.9,48.0
1,North & Middle Andaman,Andaman & Nicobar Islands,84.0,41.0,3.8,83.7,97.7,8.6,86.4,61.3,2.1,62.1,30.4,62.5,51.9,47.8
2,South Andaman,Andaman & Nicobar Islands,86.7,57.5,2.8,81.0,99.5,10.0,89.3,91.9,1.2,57.7,43.4,57.6,51.9,43.2
3,Srikakulam,Andhra Pradesh,64.3,42.5,5.5,67.5,97.9,13.8,71.6,74.7,75.6,62.6,59.6,62.8,51.9,59.2
4,Vizianagaram,Andhra Pradesh,58.3,37.6,12.7,59.6,99.0,16.9,61.7,60.3,76.7,64.0,66.7,64.6,51.9,73.9

In [2]:
state_anemia = (
    df.groupby("State")[
        "Women_Anemia"
    ]
    .mean()
    .sort_values(ascending=False)
)

print("State-wise average anemia prevalence:")
display(state_anemia)

State-wise average anemia prevalence:

State
Ladakh                                    92.750000
West Bengal                               71.526316
Tripura                                   67.050000
Jammu & Kashmir                           66.930000
Jharkhand                                 66.275000
Assam                                     65.745455
Bihar                                     64.684211
Gujarat                                   64.569697
Odisha                                    64.303333
Chhattisgarh                              63.011111
Haryana                                   60.681818
Chandigarh                                60.300000
Andhra Pradesh                            59.015385
Punjab                                    58.772727
Dadra and Nagar Haveli & Daman and Diu    58.500000
Telangana                                 58.448387
Rajasthan                                 55.433333
Madhya Pradesh                            55.184314
Meghalaya                                 54.945455
Maharastra                                54.702778
Himachal Pradesh                          54.166667
Tamil Nadu                                53.915625
Andaman & Nicobar Islands                 52.700000
Uttar Pradesh                             50.445333
NCT of Delhi                              49.500000
Karnataka                                 48.213333
Puducherry                                48.175000
Sikkim                                    40.625000
Uttarakhand                               40.169231
Arunachal Pradesh                         38.850000
Goa                                       38.800000
Kerala                                    35.728571
Mizoram                                   34.100000
Nagaland                                  29.209091
Manipur                                   28.733333
 Lakshadweep                              25.800000
Name: Women_Anemia, dtype: float64

In [3]:
# Create a summarized representation of important indicators at state level

state_summary = (
    df.groupby("State")
    .agg(
        Average_Women_Anemia=(
            "Women_Anemia",
            "mean"
        ),
        Average_Children_Anemia=(
            "Children_Anemia",
            "mean"
        ),
        Average_Low_BMI=(
            "Low_BMI",
            "mean"
        ),
        Average_Literacy=(
            "Women_Literacy",
            "mean"
        ),
        Average_IFA_Consumption=(
            "IFA_Consumption",
            "mean"
        )
    )
    .reset_index()
)

display(state_summary.head(10))

,State,Average_Women_Anemia,Average_Children_Anemia,Average_Low_BMI,Average_Literacy,Average_IFA_Consumption
0,Lakshadweep,25.800000,43.100000,8.000000,96.500000,80.100000
1,Andaman & Nicobar Islands,52.700000,37.166667,8.933333,86.066667,79.100000
2,Andhra Pradesh,59.015385,63.476923,15.123077,67.646154,69.900000
3,Arunachal Pradesh,38.850000,56.625000,4.810000,73.100000,22.345000
4,Assam,65.745455,69.818182,17.148485,77.403030,48.093939
5,Bihar,64.684211,70.076316,25.876316,57.642105,18.452632
6,Chandigarh,60.300000,54.600000,13.000000,83.000000,73.900000
7,Chhattisgarh,63.011111,69.000000,24.985185,70.107407,44.437037
8,Dadra and Nagar Haveli & Daman and Diu,58.500000,73.366667,21.900000,83.166667,61.133333
9,Goa,38.800000,52.600000,13.800000,93.100000,88.500000

In [4]:
# Calculate district-level anemia prevalence

district_anemia = df[
    [
        "District",
        "State",
        "Women_Anemia"
    ]
].copy()

district_anemia = district_anemia.sort_values(
    by="Women_Anemia",
    ascending=False
)

display(district_anemia.head(10))

               District             State  Women_Anemia
295        Leh(Ladakh)             Ladakh          93.5
296             Kargil             Ladakh          92.0
222           Kishtwar    Jammu & Kashmir          84.8
197      Lahul & Spiti   Himachal Pradesh          82.1
691   Dakshin Dinajpur        West Bengal          82.0
703  Paschim Medinipur        West Bengal          81.5
56            Udalguri              Assam          81.5
234              Pakur          Jharkhand          79.7
129           Kodagaon       Chhattisgarh          79.7
160     Chhota Udaipur            Gujarat          78.9

In [5]:
# Identify the 10 districts with the highest women's anemia prevalence

top10_districts = district_anemia.head(10)

display(top10_districts)

               District             State  Women_Anemia
295        Leh(Ladakh)             Ladakh          93.5
296             Kargil             Ladakh          92.0
222           Kishtwar    Jammu & Kashmir          84.8
197      Lahul & Spiti   Himachal Pradesh          82.1
691   Dakshin Dinajpur        West Bengal          82.0
703  Paschim Medinipur        West Bengal          81.5
56            Udalguri              Assam          81.5
234              Pakur          Jharkhand          79.7
129           Kodagaon       Chhattisgarh          79.7
160     Chhota Udaipur            Gujarat          78.9

In [6]:
# Create a composite Risk Score for each district

df["Risk Score"] = (
    0.35 * df["Women_Anemia"]
    + 0.20 * df["Low_BMI"]
    + 0.15 * (100 - df["Improved_Sanitation"])
    + 0.15 * (100 - df["Women_Literacy"])
    + 0.15 * (100 - df["IFA_Consumption"])
)

print("Risk Score created successfully.")

display(
    df[
        ["District", "State", "Risk Score"]
    ].head()
)

Risk Score created successfully.

                  District                      State  Risk Score
0                 Nicobars  Andaman & Nicobar Islands      23.505
1  North & Middle Andaman   Andaman & Nicobar Islands      30.340
2           South Andaman   Andaman & Nicobar Islands      28.645
3              Srikakulam              Andhra Pradesh      39.160
4            Vizianagaram              Andhra Pradesh      43.840

In [7]:
# Rank districts according to their Risk Score

risk_ranking = (
    df[
        [
            "District",
            "State",
            "Women_Anemia",
            "Risk Score"
        ]
    ]
    .sort_values(
        by="Risk Score",
        ascending=False
    )
    .reset_index(drop=True)
)

print("District risk ranking created successfully.")

display(risk_ranking.head(15))

District risk ranking created successfully.

                District         State  Women_Anemia  Risk Score
0                 Pakur      Jharkhand          79.7      64.550
1                 Sukma   Chhattisgarh          78.4      63.800
2               Bijapur   Chhattisgarh          72.1      62.545
3                Araria          Bihar          67.9      60.820
4                 Jamui          Bihar          75.2      60.405
5                Purnia          Bihar          66.0      60.010
6             Madhepura          Bihar          65.7      59.830
7               Saharsa          Bihar          65.3      59.700
8           Leh(Ladakh)         Ladakh          93.5      59.540
9               Deoghar      Jharkhand          70.2      58.925
10                Dumka      Jharkhand          73.4      58.775
11            Sahibganj      Jharkhand          71.5      58.760
12  Pashchimi Singhbhum      Jharkhand          72.6      58.295
13              Katihar          Bihar          68.4      57.645
14              Jamtara      Jharkhand          77.7      57.105

In [8]:
# Categorize districts according to their Risk Score

df["Risk Category"] = pd.cut(
    df["Risk Score"],
    bins=[-np.inf, 25, 50, 75, np.inf],
    labels=[
        "Low",
        "Moderate",
        "High",
        "Very High"
    ]
)

display(
    df[
        [
            "District",
            "State",
            "Risk Score",
            "Risk Category"
        ]
    ].head(10)
)

,District,State,Risk Score,Risk Category
0,Nicobars,Andaman & Nicobar Islands,23.505,Low
1,North & Middle Andaman,Andaman & Nicobar Islands,30.340,Moderate
2,South Andaman,Andaman & Nicobar Islands,28.645,Moderate
3,Srikakulam,Andhra Pradesh,39.160,Moderate
4,Vizianagaram,Andhra Pradesh,43.840,Moderate
5,Visakhapatnam,Andhra Pradesh,35.435,Moderate
6,East Godavari,Andhra Pradesh,36.345,Moderate
7,West Godavari,Andhra Pradesh,32.980,Moderate
8,Krishna,Andhra Pradesh,36.375,Moderate
9,Guntur,Andhra Pradesh,33.695,Moderate

In [9]:
# Count the number of districts in each Risk Category

risk_category_summary = (
    df["Risk Category"]
    .value_counts()
    .sort_index()
)

display(risk_category_summary)

Risk Category
Low           41
Moderate     586
High          79
Very High      0
Name: count, dtype: int64

In [10]:
# Save the aggregated results for use in later stages

state_summary.to_excel(
    "State_Wise_Anemia_Summary.xlsx",
    index=False
)

risk_ranking.to_excel(
    "District_Risk_Ranking.xlsx",
    index=False
)

df.to_excel(
    "Anemia_Data_With_Risk_Score.xlsx",
    index=False
)

print("Stage 5 outputs saved successfully!")

Stage 5 outputs saved successfully!

In [11]:
# Display the final high-risk district representation

print("Top 15 districts according to the Risk Score:")

display(
    risk_ranking.head(15)
)

Top 15 districts according to the Risk Score:

                District         State  Women_Anemia  Risk Score
0                 Pakur      Jharkhand          79.7      64.550
1                 Sukma   Chhattisgarh          78.4      63.800
2               Bijapur   Chhattisgarh          72.1      62.545
3                Araria          Bihar          67.9      60.820
4                 Jamui          Bihar          75.2      60.405
5                Purnia          Bihar          66.0      60.010
6             Madhepura          Bihar          65.7      59.830
7               Saharsa          Bihar          65.3      59.700
8           Leh(Ladakh)         Ladakh          93.5      59.540
9               Deoghar      Jharkhand          70.2      58.925
10                Dumka      Jharkhand          73.4      58.775
11            Sahibganj      Jharkhand          71.5      58.760
12  Pashchimi Singhbhum      Jharkhand          72.6      58.295
13              Katihar          Bihar          68.4      57.645
14              Jamtara      Jharkhand          77.7      57.105